// Auto-generated by: pnpm db:generate
// Hand-written initially; regenerate after running migrations against local Supabase

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      households: {
        Row: {
          id: string
          name: string
          invite_code: string
          invite_expires_at: string
          owner_id: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          invite_code: string
          invite_expires_at: string
          owner_id: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          invite_code?: string
          invite_expires_at?: string
          owner_id?: string
          created_at?: string
        }
        Relationships: []
      }
      household_members: {
        Row: {
          id: string
          household_id: string
          user_id: string
          role: 'owner' | 'member'
          display_name: string | null
          avatar_url: string | null
          joined_at: string
        }
        Insert: {
          id?: string
          household_id: string
          user_id: string
          role?: 'owner' | 'member'
          display_name?: string | null
          avatar_url?: string | null
          joined_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          user_id?: string
          role?: 'owner' | 'member'
          display_name?: string | null
          avatar_url?: string | null
          joined_at?: string
        }
        Relationships: []
      }
      pantry_items: {
        Row: {
          id: string
          household_id: string | null
          user_id: string
          name: string
          category: string | null
          quantity: number | null
          unit: string | null
          price: number | null
          expiration_date: string | null
          store: string | null
          barcode: string | null
          created_at: string
        }
        Insert: {
          id?: string
          household_id?: string | null
          user_id: string
          name: string
          category?: string | null
          quantity?: number | null
          unit?: string | null
          price?: number | null
          expiration_date?: string | null
          store?: string | null
          barcode?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          household_id?: string | null
          user_id?: string
          name?: string
          category?: string | null
          quantity?: number | null
          unit?: string | null
          price?: number | null
          expiration_date?: string | null
          store?: string | null
          barcode?: string | null
          created_at?: string
        }
        Relationships: []
      }
      item_history: {
        Row: {
          id: string
          item_id: string | null
          household_id: string | null
          user_id: string
          action: string
          reason: string | null
          snapshot: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          item_id?: string | null
          household_id?: string | null
          user_id: string
          action: string
          reason?: string | null
          snapshot?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          item_id?: string | null
          household_id?: string | null
          user_id?: string
          action?: string
          reason?: string | null
          snapshot?: Json | null
          created_at?: string
        }
        Relationships: []
      }
      shopping_suggestions: {
        Row: {
          id: string
          household_id: string | null
          name: string
          category: string | null
          added_by: string | null
          is_checked: boolean
          created_at: string
        }
        Insert: {
          id?: string
          household_id?: string | null
          name: string
          category?: string | null
          added_by?: string | null
          is_checked?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          household_id?: string | null
          name?: string
          category?: string | null
          added_by?: string | null
          is_checked?: boolean
          created_at?: string
        }
        Relationships: []
      }
      meal_plans: {
        Row: {
          id: string
          household_id: string
          user_id: string
          planned_date: string
          meal_type: 'breakfast' | 'lunch' | 'dinner' | 'snack'
          recipe_name: string
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          household_id: string
          user_id: string
          planned_date: string
          meal_type: 'breakfast' | 'lunch' | 'dinner' | 'snack'
          recipe_name: string
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          user_id?: string
          planned_date?: string
          meal_type?: 'breakfast' | 'lunch' | 'dinner' | 'snack'
          recipe_name?: string
          notes?: string | null
          created_at?: string
        }
        Relationships: []
      }
      budget_accounts: {
        Row: {
          id: string
          household_id: string
          name: string
          type: 'checking' | 'savings' | 'credit' | 'cash' | 'investment'
          balance: number
          currency: string
          is_shared: boolean
          created_by: string
          created_at: string
        }
        Insert: {
          id?: string
          household_id: string
          name: string
          type: 'checking' | 'savings' | 'credit' | 'cash' | 'investment'
          balance?: number
          currency?: string
          is_shared?: boolean
          created_by: string
          created_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          name?: string
          type?: 'checking' | 'savings' | 'credit' | 'cash' | 'investment'
          balance?: number
          currency?: string
          is_shared?: boolean
          created_by?: string
          created_at?: string
        }
        Relationships: []
      }
      budget_categories: {
        Row: {
          id: string
          household_id: string
          name: string
          monthly_limit: number | null
          color: string | null
          icon: string | null
          created_at: string
        }
        Insert: {
          id?: string
          household_id: string
          name: string
          monthly_limit?: number | null
          color?: string | null
          icon?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          name?: string
          monthly_limit?: number | null
          color?: string | null
          icon?: string | null
          created_at?: string
        }
        Relationships: []
      }
      transactions: {
        Row: {
          id: string
          household_id: string
          account_id: string
          category_id: string | null
          user_id: string
          amount: number
          description: string
          merchant: string | null
          transaction_date: string
          is_recurring: boolean
          recurrence_rule: string | null
          notes: string | null
          category: string | null
          emotion: string | null
          created_at: string
        }
        Insert: {
          id?: string
          household_id: string
          account_id: string
          category_id?: string | null
          user_id: string
          amount: number
          description: string
          merchant?: string | null
          transaction_date: string
          is_recurring?: boolean
          recurrence_rule?: string | null
          notes?: string | null
          category?: string | null
          emotion?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          account_id?: string
          category_id?: string | null
          user_id?: string
          amount?: number
          description?: string
          merchant?: string | null
          transaction_date?: string
          is_recurring?: boolean
          recurrence_rule?: string | null
          notes?: string | null
          category?: string | null
          emotion?: string | null
          created_at?: string
        }
        Relationships: []
      }
      nutrition_goals: {
        Row: {
          id: string
          user_id: string
          household_id: string
          calories_goal: number | null
          protein_g: number | null
          carbs_g: number | null
          fat_g: number | null
          fiber_g: number | null
          water_ml: number | null
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          household_id: string
          calories_goal?: number | null
          protein_g?: number | null
          carbs_g?: number | null
          fat_g?: number | null
          fiber_g?: number | null
          water_ml?: number | null
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          household_id?: string
          calories_goal?: number | null
          protein_g?: number | null
          carbs_g?: number | null
          fat_g?: number | null
          fiber_g?: number | null
          water_ml?: number | null
          updated_at?: string
        }
        Relationships: []
      }
      food_entries: {
        Row: {
          id: string
          user_id: string
          household_id: string
          entry_date: string
          meal_type: 'breakfast' | 'lunch' | 'dinner' | 'snack'
          food_name: string
          brand: string | null
          serving_size: number | null
          serving_unit: string | null
          calories: number
          protein_g: number | null
          carbs_g: number | null
          fat_g: number | null
          fiber_g: number | null
          sodium_mg: number | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          household_id: string
          entry_date: string
          meal_type: 'breakfast' | 'lunch' | 'dinner' | 'snack'
          food_name: string
          brand?: string | null
          serving_size?: number | null
          serving_unit?: string | null
          calories: number
          protein_g?: number | null
          carbs_g?: number | null
          fat_g?: number | null
          fiber_g?: number | null
          sodium_mg?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          household_id?: string
          entry_date?: string
          meal_type?: 'breakfast' | 'lunch' | 'dinner' | 'snack'
          food_name?: string
          brand?: string | null
          serving_size?: number | null
          serving_unit?: string | null
          calories?: number
          protein_g?: number | null
          carbs_g?: number | null
          fat_g?: number | null
          fiber_g?: number | null
          sodium_mg?: number | null
          created_at?: string
        }
        Relationships: []
      }
      exercises: {
        Row: {
          id: string
          household_id: string | null
          name: string
          muscle_group: string | null
          equipment: string | null
          notes: string | null
          is_custom: boolean
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          household_id?: string | null
          name: string
          muscle_group?: string | null
          equipment?: string | null
          notes?: string | null
          is_custom?: boolean
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          household_id?: string | null
          name?: string
          muscle_group?: string | null
          equipment?: string | null
          notes?: string | null
          is_custom?: boolean
          created_by?: string | null
          created_at?: string
        }
        Relationships: []
      }
      workout_sessions: {
        Row: {
          id: string
          user_id: string
          household_id: string
          started_at: string
          ended_at: string | null
          title: string | null
          notes: string | null
          duration_minutes: number | null
        }
        Insert: {
          id?: string
          user_id: string
          household_id: string
          started_at: string
          ended_at?: string | null
          title?: string | null
          notes?: string | null
        }
        Update: {
          user_id?: string
          household_id?: string
          started_at?: string
          ended_at?: string | null
          title?: string | null
          notes?: string | null
        }
        Relationships: []
      }
      session_exercises: {
        Row: {
          id: string
          session_id: string
          exercise_id: string
          set_number: number
          reps: number | null
          weight_kg: number | null
          duration_s: number | null
          distance_m: number | null
          notes: string | null
        }
        Insert: {
          id?: string
          session_id: string
          exercise_id: string
          set_number: number
          reps?: number | null
          weight_kg?: number | null
          duration_s?: number | null
          distance_m?: number | null
          notes?: string | null
        }
        Update: {
          id?: string
          session_id?: string
          exercise_id?: string
          set_number?: number
          reps?: number | null
          weight_kg?: number | null
          duration_s?: number | null
          distance_m?: number | null
          notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'session_exercises_exercise_id_fkey'
            columns: ['exercise_id']
            isOneToOne: false
            referencedRelation: 'exercises'
            referencedColumns: ['id']
          }
        ]
      }
      health_metrics: {
        Row: {
          id: string
          user_id: string
          household_id: string
          source: 'garmin' | 'bevel' | 'manual'
          metric_date: string
          steps: number | null
          calories_burned: number | null
          active_minutes: number | null
          heart_rate_avg: number | null
          sleep_hours: number | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          household_id: string
          source: 'garmin' | 'bevel' | 'manual'
          metric_date: string
          steps?: number | null
          calories_burned?: number | null
          active_minutes?: number | null
          heart_rate_avg?: number | null
          sleep_hours?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          household_id?: string
          source?: 'garmin' | 'bevel' | 'manual'
          metric_date?: string
          steps?: number | null
          calories_burned?: number | null
          active_minutes?: number | null
          heart_rate_avg?: number | null
          sleep_hours?: number | null
          created_at?: string
        }
        Relationships: []
      }
      journal_entries: {
        Row: {
          id: string
          user_id: string
          household_id: string
          title: string | null
          body: string
          mood: 'great' | 'good' | 'okay' | 'low' | 'bad' | null
          tags: string[] | null
          is_private: boolean
          entry_date: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          household_id: string
          title?: string | null
          body: string
          mood?: 'great' | 'good' | 'okay' | 'low' | 'bad' | null
          tags?: string[] | null
          is_private?: boolean
          entry_date: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          household_id?: string
          title?: string | null
          body?: string
          mood?: 'great' | 'good' | 'okay' | 'low' | 'bad' | null
          tags?: string[] | null
          is_private?: boolean
          entry_date?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      school_classes: {
        Row: {
          id: string
          user_id: string
          household_id: string
          name: string
          instructor: string | null
          color: string | null
          semester: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          household_id: string
          name: string
          instructor?: string | null
          color?: string | null
          semester?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          household_id?: string
          name?: string
          instructor?: string | null
          color?: string | null
          semester?: string | null
          created_at?: string
        }
        Relationships: []
      }
      assignments: {
        Row: {
          id: string
          user_id: string
          household_id: string
          class_id: string | null
          title: string
          description: string | null
          due_date: string | null
          status: 'todo' | 'in_progress' | 'submitted' | 'graded'
          grade: number | null
          grade_scale: string | null
          weight_pct: number | null
          notes: string | null
          provider: 'manual' | 'canvas'
          external_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          household_id: string
          class_id?: string | null
          title: string
          description?: string | null
          due_date?: string | null
          status?: 'todo' | 'in_progress' | 'submitted' | 'graded'
          grade?: number | null
          grade_scale?: string | null
          weight_pct?: number | null
          notes?: string | null
          provider?: 'manual' | 'canvas'
          external_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          household_id?: string
          class_id?: string | null
          title?: string
          description?: string | null
          due_date?: string | null
          status?: 'todo' | 'in_progress' | 'submitted' | 'graded'
          grade?: number | null
          grade_scale?: string | null
          weight_pct?: number | null
          notes?: string | null
          provider?: 'manual' | 'canvas'
          external_id?: string | null
          created_at?: string
        }
        Relationships: []
      }
      devotional_plans: {
        Row: {
          id: string
          household_id: string
          created_by: string
          title: string
          description: string | null
          total_days: number
          start_date: string | null
          created_at: string
        }
        Insert: {
          id?: string
          household_id: string
          created_by: string
          title: string
          description?: string | null
          total_days: number
          start_date?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          created_by?: string
          title?: string
          description?: string | null
          total_days?: number
          start_date?: string | null
          created_at?: string
        }
        Relationships: []
      }
      devotional_progress: {
        Row: {
          id: string
          plan_id: string
          user_id: string
          day_number: number
          completed_at: string | null
          notes: string | null
        }
        Insert: {
          id?: string
          plan_id: string
          user_id: string
          day_number: number
          completed_at?: string | null
          notes?: string | null
        }
        Update: {
          id?: string
          plan_id?: string
          user_id?: string
          day_number?: number
          completed_at?: string | null
          notes?: string | null
        }
        Relationships: []
      }
      prayer_requests: {
        Row: {
          id: string
          user_id: string
          household_id: string
          title: string
          body: string | null
          is_answered: boolean
          answered_at: string | null
          is_private: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          household_id: string
          title: string
          body?: string | null
          is_answered?: boolean
          answered_at?: string | null
          is_private?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          household_id?: string
          title?: string
          body?: string | null
          is_answered?: boolean
          answered_at?: string | null
          is_private?: boolean
          created_at?: string
        }
        Relationships: []
      }
      scripture_notes: {
        Row: {
          id: string
          user_id: string
          household_id: string
          reference: string
          translation: string | null
          body: string | null
          tags: string[] | null
          is_private: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          household_id: string
          reference: string
          translation?: string | null
          body?: string | null
          tags?: string[] | null
          is_private?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          household_id?: string
          reference?: string
          translation?: string | null
          body?: string | null
          tags?: string[] | null
          is_private?: boolean
          created_at?: string
        }
        Relationships: []
      }
      integration_tokens: {
        Row: {
          id: string
          user_id: string
          provider: 'garmin' | 'bevel' | 'canvas'
          access_token: string
          refresh_token: string | null
          expires_at: string | null
          scope: string | null
          metadata: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          provider: 'garmin' | 'bevel' | 'canvas'
          access_token: string
          refresh_token?: string | null
          expires_at?: string | null
          scope?: string | null
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          provider?: 'garmin' | 'bevel' | 'canvas'
          access_token?: string
          refresh_token?: string | null
          expires_at?: string | null
          scope?: string | null
          metadata?: Json | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      app_shortcuts: {
        Row: {
          id: string
          household_id: string
          user_id: string
          label: string
          url: string
          icon: string | null
          module: string | null
          created_at: string
        }
        Insert: {
          id?: string
          household_id: string
          user_id: string
          label: string
          url: string
          icon?: string | null
          module?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          user_id?: string
          label?: string
          url?: string
          icon?: string | null
          module?: string | null
          created_at?: string
        }
        Relationships: []
      }
      activity_feed: {
        Row: {
          id: string
          household_id: string
          user_id: string
          module: string
          action: string
          payload: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          household_id: string
          user_id: string
          module: string
          action: string
          payload?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          household_id?: string
          user_id?: string
          module?: string
          action?: string
          payload?: Json | null
          created_at?: string
        }
        Relationships: []
      }
      webauthn_credentials: {
        Row: {
          id: string
          user_id: string
          credential_id: string
          public_key: string
          counter: number
          device_name: string | null
          transports: string | null
          backed_up: boolean | null
          created_at: string
          last_used_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          credential_id: string
          public_key: string
          counter?: number
          device_name?: string | null
          transports?: string | null
          backed_up?: boolean | null
          created_at?: string
          last_used_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          credential_id?: string
          public_key?: string
          counter?: number
          device_name?: string | null
          transports?: string | null
          backed_up?: boolean | null
          created_at?: string
          last_used_at?: string | null
        }
        Relationships: []
      }
      webauthn_challenges: {
        Row: {
          id: string
          user_id: string | null
          challenge: string
          expires_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          challenge: string
          expires_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          challenge?: string
          expires_at?: string
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: {
      join_household: {
        Args: { p_invite_code: string }
        Returns: string
      }
    }
    Enums: Record<string, never>
  }
}
